#!/bin/sh
cd ${0%/*}
jsduck --config jsduck-conf.json -o html      
wait
cp images/ice-logo.png html/resources/images/ice-logo.png
cp images/bridgeIt-logo.png html/resources/images/bridgeIt-logo.png
cp -f images/favicon.ico html/favicon.ico
cat ./html/template.html | sed 's/<\/head>/<link rel="stylesheet" href="..\/overrides.css"\/><\/head>/g' > ./html/index.html